# These are supported funding model platforms

github: [mrcartoonster]
ko_fi: mrcartoonster
custom: ["<script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="mrcartoontser" data-color="#FFDD00" data-emoji=""  data-font="Cookie" data-text="Buy me a coffee" data-outline-color="#000" data-font-color="#000" data-coffee-color="#fff" ></script>", "https://www.buymeacoffee.com/mrcartoontser"]
