# These are supported funding model platforms

github: [mrcartoonster]
ko_fi: mrcartoonster
custom: ["https://www.buymeacoffee.com/mrcartoontser", mrcartoonster, "https://paypal.me/mrcartoonster?locale.x=en_US"]
