# These are supported funding model platforms

github: [mrcartoonster]
ko_fi: mrcartoonster
custom: "https://paypal.me/mrcartoonster?locale.x=en_US"
custom: "https://www.buymeacoffee.com/mrcartoontser"
