# These are supported funding model platforms

github: [mrcartoonster]
ko_fi: mrcartoosnter
custom: ["https://www.buymeacoffee.com/mrcartoontser", mrcartoonster]
custom: ["https://paypal.me/mrcartoonster?locale.x=en_US", mrcartoonster]
